"""add is_encrypted to files

Revision ID: c39711cb68d8
Revises: c8f7af86c6cc
Create Date: 2026-05-09 11:22:21.975210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39711cb68d8'
down_revision = 'c8f7af86c6cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_encrypted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('is_encrypted')

    # ### end Alembic commands ###
