"""add webauthn columns

Revision ID: c8f7af86c6cc
Revises: 70d0906f4f80
Create Date: 2026-05-07 15:53:37.830440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f7af86c6cc'
down_revision = '70d0906f4f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webauthn_credential_id', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('webauthn_public_key', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('webauthn_sign_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('webauthn_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('webauthn_enabled')
        batch_op.drop_column('webauthn_sign_count')
        batch_op.drop_column('webauthn_public_key')
        batch_op.drop_column('webauthn_credential_id')

    # ### end Alembic commands ###
