"""fim_tables_full

Revision ID: e86b934f526e
Revises: c39711cb68d8
Create Date: 2026-06-09 15:28:46.749911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86b934f526e'
down_revision = 'c39711cb68d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('check_interval_mins', sa.Integer(), nullable=False),
    sa.Column('alert_on_tamper', sa.Boolean(), nullable=False),
    sa.Column('alert_on_missing', sa.Boolean(), nullable=False),
    sa.Column('alert_on_size_change', sa.Boolean(), nullable=False),
    sa.Column('email_alert', sa.Boolean(), nullable=False),
    sa.Column('socket_alert', sa.Boolean(), nullable=False),
    sa.Column('severity_default', sa.String(length=10), nullable=False),
    sa.Column('max_file_size_mb', sa.Integer(), nullable=True),
    sa.Column('excluded_extensions', sa.Text(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('integrity_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('captured_by_id', sa.Integer(), nullable=True),
    sa.Column('capture_reason', sa.String(length=20), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('supersede_note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['captured_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrity_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('computed_sha256', sa.String(length=64), nullable=True),
    sa.Column('file_size_at_check', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('check_duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['baseline_id'], ['integrity_baselines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrity_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('raised_at', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_hash', sa.String(length=64), nullable=False),
    sa.Column('found_hash', sa.String(length=64), nullable=True),
    sa.Column('expected_size', sa.BigInteger(), nullable=True),
    sa.Column('found_size', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolution_type', sa.String(length=30), nullable=True),
    sa.Column('resolution_note', sa.String(length=1000), nullable=True),
    sa.Column('escalated_to_id', sa.Integer(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('socket_emitted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['check_id'], ['integrity_checks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['escalated_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['integrity_alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitoring_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('policy_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('last_checked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_check_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('check_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('alert_count', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'monitoring_policies', ['policy_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_policy_id', sa.Integer(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'user'"))
        batch_op.create_foreign_key(None, 'monitoring_policies', ['default_policy_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'user'"))
        batch_op.drop_column('default_policy_id')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('alert_count')
        batch_op.drop_column('check_count')
        batch_op.drop_column('next_check_at')
        batch_op.drop_column('last_checked_at')
        batch_op.drop_column('current_status')
        batch_op.drop_column('policy_id')
        batch_op.drop_column('monitoring_enabled')

    op.drop_table('alert_comments')
    op.drop_table('integrity_alerts')
    op.drop_table('integrity_checks')
    op.drop_table('integrity_baselines')
    op.drop_table('monitoring_policies')
    # ### end Alembic commands ###
