name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create deployment package
        run: zip -r deploy.zip . -x "*.git*" -x "instance/*" -x "vault_uploads/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "FINAL PROJECT"
          environment_name: "filevault-prod"
          region: "us-east-1"
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
